emsite/emapp/urls.py
from django.urls import path

from . import views

app_name = 'emapp'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('trans-list', views.TransactionList.as_view(), name='trans_list'),
    path('<int:pk>/update', views.TransactionUpdate.as_view(), name='trans_update'),
    path('create', views.TransactionCreate.as_view(), name='trans_create'),

    path('src-create', views.SourceCreate.as_view(), name='src_create'),
    path('<int:pk>/src-update', views.SourceUpdate.as_view(), name='src_update'),
    path('src-list', views.SourceList.as_view(), name='src_list'),

    path('cat-create', views.CategoryCreate.as_view(), name='cat_create'),
    path('<int:pk>/cat-update', views.CategoryUpdate.as_view(), name='cat_update'),
    path('cat-list', views.CategoryList.as_view(), name='cat_list'),
]

emsite/emsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('emapp.urls')),
    path('admin/', admin.site.urls),
]

emsite/emapp/models.py
from django.db import models
from django.urls import reverse


class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Source(BaseModel):
    SRC_TYPES = (
        ('S', 'Savings Acct'),
        ('C', 'Credit Card')
    )
    name = models.CharField(unique=True, max_length=50, help_text="Source Name")
    src_type = models.TextField(choices=SRC_TYPES, verbose_name="Source Type", help_text="Source Type")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('emapp:home')


class Category(BaseModel):    
    name = models.CharField(max_length=50, help_text="Category Name", unique=True)    

    class Meta:        
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('emapp:home')


class Transaction(BaseModel):
    TRAN_TYPE = (
        ('CR', 'Credit'),
        ('DB', 'Debit')
    )
    amount = models.FloatField(help_text="Transaction Amount")
    date = models.DateTimeField(help_text="Transaction Date")
    src = models.ForeignKey(Source, on_delete=models.CASCADE, related_name="transactions")    
    desc = models.CharField(help_text="Description", max_length=200, verbose_name="Description")
    typ = models.CharField(choices=TRAN_TYPE, help_text="Transaction Type", max_length=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="transactions")
    pending = models.BooleanField(help_text="Is transaction cycle is pending?", default=True)
    include_in_calcultion = models.BooleanField(help_text="Include in any calculations?", default=True)

    def __str__(self):
        return "{} - {}".format(self.amount, self.date)

    def get_absolute_url(self):
        return reverse('emapp:home')

emsite/emapp/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, UpdateView
from django.views.generic.edit import CreateView
from django.db.models import Sum

from . models import Source, Transaction, Category


class Home(ListView):
    model = Transaction
    context_object_name = 'transactions'
    template_name = 'emapp/home.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.all().order_by('-date')[:5]

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['ttl_trans_amt'] = Transaction.objects.aggregate(Sum('amount'))['amount__sum']
        context['tran_cnt'] = Transaction.objects.count()
        context['cat_cnt'] = Category.objects.all().count()
        context['src_cnt'] = Source.objects.all().count()
        context['categories'] = Category.objects.all()[:8]
        context['sources'] = Source.objects.all()[:8]
        context['show_view_all'] = True

        citi_credit = Source.objects.get(name="CITI - CreditCard")
        ktk_credit = Source.objects.get(name="Kotak - CreditCard")
        dbs_svg = Source.objects.get(name="DBS - Saving")
        citi_savings = Source.objects.get(name="CITI - Saving")
        stats = {}
        stats['CITI - CreditCard'] = Transaction.objects.all().filter(src=citi_credit).aggregate(Sum('amount'))['amount__sum']
        stats['Kotak - CreditCard'] = Transaction.objects.all().filter(src=ktk_credit).aggregate(Sum('amount'))['amount__sum']
        stats['DBS - Saving'] = Transaction.objects.all().filter(src=dbs_svg).aggregate(Sum('amount'))['amount__sum']
        stats['CITI - Savings'] = Transaction.objects.all().filter(src=citi_savings).aggregate(Sum('amount'))['amount__sum'] or 0
        context['stats'] = stats

        return context


class TransactionList(ListView):
    model = Transaction
    context_object_name = 'transactions'
    template_name = 'emapp/generic_display.html'
    paginate_by = 25

    def get_queryset(self):
        qs = super().get_queryset()
        cat = self.request.GET.get('cat')
        src = self.request.GET.get('src')
        if cat:
            qs = qs.filter(category=cat)
        if src:
            qs = qs.filter(src=src)
        return qs.all().order_by('-date') 

    def get_context_data(self, **kwargs):
        context = super(TransactionList, self).get_context_data(**kwargs)
        context['show_view_all'] = False
        context['page'] = 'emapp/trans_list.html'
        context['tran_cnt'] = Transaction.objects.all().count()
        return context   


class TransactionUpdate(UpdateView):
    model = Transaction
    fields = ['amount', 'date', 'src', 'typ', 'category', 'desc', 'pending', 'include_in_calcultion']
    template_name = 'emapp/trans_update.html'


class TransactionCreate(CreateView):
    model = Transaction
    fields = ['amount', 'date', 'typ', 'src', 'category', 'desc', 'pending', 'include_in_calcultion']
    template_name = 'emapp/trans_create.html'


class SourceCreate(CreateView):
    model = Source
    fields = ['name', 'src_type']
    template_name = 'emapp/src_create.html'


class SourceUpdate(UpdateView):
    model = Source
    fields = ['name', 'src_type']
    template_name = 'emapp/src_create.html'


class SourceList(ListView):
    model = Source
    context_object_name = "sources"
    template_name = 'emapp/generic_display.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super(SourceList, self).get_context_data(**kwargs)
        context['show_view_all'] = False
        context['page'] = 'emapp/src_list.html'
        context['src_cnt'] = Source.objects.all().count()
        return context


class CategoryCreate(CreateView):
    model = Category
    fields = ['name']
    template_name = 'emapp/cat_create.html'


class CategoryUpdate(UpdateView):
    model = Category
    fields = ['name']
    template_name = 'emapp/cat_create.html'


class CategoryList(ListView):
    model = Category
    context_object_name = "categories"
    template_name = 'emapp/generic_display.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super(CategoryList, self).get_context_data(**kwargs)
        context['show_view_all'] = False
        context['page'] = 'emapp/cat_list.html'
        context['cat_cnt'] = Category.objects.all().count()        
        return context

emsite/emapp/templates/emapp/cat_create.html
{% extends "emapp/index.html" %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="card">
        <div class="card-header">
          <h2>Category Create</h2>      
        </div>
    
        <div class="card-body">

            <form method="post">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Save Category</button>
            </form>

        </div>

    </div>

{% endblock content %}

emsite/emapp/templates/emapp/cat_list.html
<div class="card">
    
    <div class="card-header">
        <h4>Categories <small>({{ cat_cnt }})</small>
            <div class="float-right">
                {% if show_view_all %}
                    <a class="btn btn-primary" href="{% url 'emapp:cat_list' %}">View All > </a>            
                {% endif %}            
                <a class="btn btn-success" href="{% url 'emapp:cat_create' %}">Create New + </a>
            </div>
        </h4>
    </div>            

    <div class="card-body">
        <table class="table table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>                        
                    <th scope="col">Transactions</th> 
                </tr>
                </thead>
                <tbody>
                    {% for category in categories %}
                        <tr>
                            <td>{{ category.pk }}</td>
                            <td><a href="{% url 'emapp:cat_update' category.pk %}">{{ category.name }}</a></td>
                            <td>
                                {{ category.transactions.count }}
                                <a href="{% url 'emapp:trans_list' %}?cat={{ category.pk }}">(view)</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
        </table>
    </div>

    {% if not show_view_all %}
        <div class="card-footer">        
            {% include "emapp/paginate.html" %}        
        </div>
    {% endif %}

</div>

emsite/emapp/templates/emapp/generic_display.html
{% extends "emapp/index.html" %}

{% block content %}

{% include page %}

{% endblock content %}

emsite/emapp/templates/emapp/home.html
{% extends "emapp/index.html" %}

{% block content %}
    
    {% include "emapp/stats.html" %}

    <hr style="background: white;">

    {% include "emapp/trans_list.html" %}

    <hr style="background: white;">

    <div class="row">
        <div class="col-6">
            {% include "emapp/cat_list.html" %}
        </div>

        <div class="col-6">        
            {% include "emapp/src_list.html" %}
        </div>

    </div>

  

{% endblock content %}
  

emsite/emapp/templates/emapp/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Expense Manager</title>    

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans&display=swap" rel="stylesheet"> 


    <style>
      body{
        background:  #464942;
      }

      .font-test{
        font-family: 'PT Sans', sans-serif;
      }

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.3/examples/starter-template/starter-template.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/">Expense Manager</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">

      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Create</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{% url 'emapp:trans_create' %}">Transaction</a>
          <a class="dropdown-item" href="{% url 'emapp:src_create' %}">Source</a>
          <a class="dropdown-item" href="{% url 'emapp:cat_create' %}">Category</a>
        </div>
      </li> -->

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'emapp:trans_list' %}">Transactions <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'emapp:cat_list' %}">Categories</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'emapp:src_list' %}">Sources</a>
        </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Create</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Transaction</a>
          <a class="dropdown-item" href="#">Source</a>
          <a class="dropdown-item" href="#">Category</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<main role="main" class="container">
    {% block content %}
    {% endblock content %}

</main><!-- /.container -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

emsite/emapp/templates/emapp/paginate.html
<nav aria-label="">
    <ul class="pagination justify-content-center mb-4">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1&q={{ request.GET.q }}">First</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}&q={{ request.GET.q }}">{{ page_obj.previous_page_number }}</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">First</span>
            </li>
        {% endif %}
            <li class="page-item active">
                <span class="page-link">
                {{ page_obj.number }}
                <span class="sr-only">(current)</span>
                </span>
            </li>
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}">{{ page_obj.next_page_number }}</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&q={{ request.GET.q }}">Last</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Last</a>
            </li>
        {% endif %}
    </ul>
</nav>
      

emsite/emapp/templates/emapp/src_create.html
{% extends "emapp/index.html" %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="card">
        <div class="card-header">
          <h2>Source Create</h2>      
        </div>
    
        <div class="card-body">
            <form method="post">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Save Source</button>
            </form>
        </div>
    
    </div>

{% endblock content %}

emsite/emapp/templates/emapp/src_list.html
<div class="card">
    <div class="card-header">
        <h4>Sources <small>({{ src_cnt }})</small>
            <div class="float-right">
                {% if show_view_all %}
                    <a class="btn btn-primary" href="{% url 'emapp:src_list' %}">View All > </a>            
                {% endif %}            
                <a class="btn btn-success" href="{% url 'emapp:src_create' %}">Create New + </a>
            </div>
        </h4>
    </div>            

    <div class="card-body">
        <table class="table table-bordered">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>                        
                <th scope="col">Type</th>
                <th scope="col">Transactions</th> 
            </tr>
            </thead>
            <tbody>
                {% for source in sources %}
                    <tr>
                        <td>{{ source.pk }}</td>
                        <td><a href="{% url 'emapp:src_update' source.pk %}">{{ source.name }}</a></td>
                        <td>{{ source.src_type }}</td>
                        <td>
                            {{ source.transactions.count }}
                            <a href="{% url 'emapp:trans_list' %}?src={{ source.pk }}">(view)</a>
                        </td>
                    </tr>
                {% endfor %}
                
            </tbody>
        </table>
    </div>

    {% if not show_view_all %}
        <div class="card-footer">        
            {% include "emapp/paginate.html" %}        
        </div>
    {% endif %}

</div>

emsite/emapp/templates/emapp/stats.html
<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container-fluid">
    <div class="row">
      {% for key, val in stats.items %}
        <div class="col-md-3">
            <div class="card text-white bg-default mb-1" style="max-width: 18rem;">                                    
                <div class="card-body" style="color: black;" align="center">
                  <h5 class="card-title">{{ key }}</h5>
                  <p class="card-text"><strong>{{ val }}</strong></p>
                </div>
            </div>
          </div>
      {% endfor %}        
    </div>    
  </div>
</main>

emsite/emapp/templates/emapp/trans_create.html
{% extends "emapp/index.html" %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="card">
        <div class="card-header">
          <h2>Transaction Create</h2>      
        </div>
    
        <div class="card-body">

            <form method="post">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Save Transaction</button>
            </form>

        </div>
        
    </div>

{% endblock content %}

emsite/emapp/templates/emapp/trans_list.html
  <div class="card font-test">
    <div class="card-header">
      <h4>Transactions <small>({{ tran_cnt }})</small>
          <div class="float-right">
              {% if show_view_all %}
                  <a class="btn btn-primary" href="{% url 'emapp:trans_list' %}">View All > </a>            
              {% endif %}            
              <a class="btn btn-success" href="{% url 'emapp:trans_create' %}">Create New + </a>
          </div>
      </h4>      
    </div>

    <div class="card-body">
      <table class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>        
            <th scope="col">Source</th>        
            <th scope="col">Category</th>
            <th scope="col">Type</th>
            <th scope="col">Descrption</th>
            <th scope="col">Pending?</th>
          </tr>
        </thead>
        <tbody>

            {% for transaction in transactions %}      
              <tr>
                <th scope="row" class="{% if transaction.typ == 'CR' %} table-success {% else %} table-danger {% endif %}">{{ transaction.pk }}</th>
                <th><a href="{% url 'emapp:trans_update' transaction.pk %}">{{ transaction.amount }}</a></th>
                <td>{{ transaction.date|date:"d M, Y"}}</td>
                <td>
                  <a href="{% url 'emapp:trans_list' %}?src={{ transaction.src.pk }}">{{ transaction.src }}</a>
                </td>
                <td>
                  <a href="{% url 'emapp:trans_list' %}?cat={{ transaction.category.pk }}">{{ transaction.category }}</a>
                </td>
                <td>{{ transaction.typ }}</td>
                <td>{{ transaction.desc }}</td>
                <td>{{ transaction.pending }}</td>            
              </tr>
            {% endfor %}
          
        </tbody>
      </table>
    </div>

    <div class="card-footer">        
        {% if not show_view_all %}      
            {% include "emapp/paginate.html" %}
            {% else %}
              <span><strong>total transactions amount = {{ ttl_trans_amt }}</strong></span>
        {% endif %}
      </div>

  </div>
  

emsite/emapp/templates/emapp/trans_update.html
{% extends "emapp/index.html" %}

{% block content %}

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <!-- <input class="btn-primary" type="submit" value="Save"> -->
        <button type="reset" class="btn btn-warning">Reset</button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock content %}